### ISSUE TITLE
aucor_core_security_disable_unfiltered_html -removes iframes (inside html -blocks) when in wide column container blocks

### ISSUE THREAD

**Issue by Jaska** [aucor/aucor-core#1]
So, I wanted to be able to put iframes in the pages and since WordPress's embed section was no use, I thought the best would be to simply use the HTML block. 
Of course I had to enable that block since it's removed by default in Aucor Starter.

I wanted the iframe to be inside the column-block which worked until I clicked the "Wide" or "Full width" buttons of the columns.

After little testing, I found out that by commenting aucor_core_security_disable_unfiltered_html in class-security.php file, it let the editor save the html content when inside wide columns.

**Comment by TeemuSuoranta** [comment]
Sorry for late reply. You can disable any feature or sub feature by filter. In this case `add_filter('aucor_core_security_disable_unfiltered_html', '__return_false');`

Here's the reason we disable unfiltered html:
- Injecting javascript or iframes is one of the most common hacks in WordPress sites when the hacker is able to inject them in content in various ways. This brings a little protection. 
- Not all roles can (by default) write with unfiltered html. This means that admin can embed iframe and later editor go save the same page and that iframe is gone because the editor won't have the right to save unfiltered html. So by having iframe/javascript right in content you run the risk of losing content by lower level users.

If you need to embed iframes straight into content, I'll recommend:
- Use plugin like [Iframe](https://wordpress.org/plugins/iframe/) that allows iframes through shortcode markup but still protects javascript
- Disable this feature

We will keep this feature on by default as this improves the security a bit and protects against content loss.

**Comment by Jaska** [comment]
Thanks for answering.

But do you see the problem that iframes can be added inside columns when not in wide of full mode?
If they would be disabled everywhere, then I'd see the point.

**Comment by TeemuSuoranta** [comment]
Sorry to keep you waiting again. The unfiltered_html option should disable iframes everywhere as it is WordPress core functionality that we are just switching on with the filter. To my knowledge, WP scans the whole content via regex on the_content filter either or both when content is saved to DB and when it is displayed (the_content hook). If it lets through something it shouldn't, it might be bug in core.

**Comment by Jaska** [comment]
Thanks!

**Comment by Jaska** [comment]
@TeemuSuoranta the code:
 add_filter('aucor_core_security_disable_unfiltered_html', '__return_false'); 

Doesn't disable the feature. I tried it with different priorities but no.
Are you sure it works?
